// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./Biography")),
  hero: dynamic(() => import("./Hero")),
};
